// This declaration is automatically generated by scripts/generate-rules.ts

export declare const pedanticRules: Record<string, unknown>;
export declare const nurseryRules: Record<string, unknown>;
export declare const styleRules: Record<string, unknown>;
export declare const correctnessRules: Record<string, unknown>;
export declare const restrictionRules: Record<string, unknown>;
export declare const suspiciousRules: Record<string, unknown>;
