// This declaration is automatically generated by scripts/generate-rules.ts

export declare const eslintRules: Record<string, unknown>;
export declare const importRules: Record<string, unknown>;
export declare const jestRules: Record<string, unknown>;
export declare const jsdocRules: Record<string, unknown>;
export declare const jsx_a11yRules: Record<string, unknown>;
export declare const nextjsRules: Record<string, unknown>;
export declare const reactRules: Record<string, unknown>;
export declare const react_perfRules: Record<string, unknown>;
export declare const tree_shakingRules: Record<string, unknown>;
export declare const typescriptRules: Record<string, unknown>;
export declare const unicornRules: Record<string, unknown>;
