// These rules are automatically generated by scripts/generate-rules.ts

import * as rules from './rules-by-category.js';

const pedanticConfig = {
  name: 'oxlint/pedantic',
  rules: rules.pedanticRules,
};

const nurseryConfig = {
  name: 'oxlint/nursery',
  rules: rules.nurseryRules,
};

const restrictionConfig = {
  name: 'oxlint/restriction',
  rules: rules.restrictionRules,
};

const styleConfig = {
  name: 'oxlint/style',
  rules: rules.styleRules,
};

const conditionalFixConfig = {
  name: 'oxlint/conditional-fix',
  rules: rules.conditionalFixRules,
};

const dangerousFixConfig = {
  name: 'oxlint/dangerous-fix',
  rules: rules.dangerousFixRules,
};

const conditionalFixSuggestionConfig = {
  name: 'oxlint/conditional-fix-suggestion',
  rules: rules.conditionalFixSuggestionRules,
};

const pendingConfig = {
  name: 'oxlint/pending',
  rules: rules.pendingRules,
};

const correctnessConfig = {
  name: 'oxlint/correctness',
  rules: rules.correctnessRules,
};

const perfConfig = {
  name: 'oxlint/perf',
  rules: rules.perfRules,
};

const conditionalSuggestionFixConfig = {
  name: 'oxlint/conditional-suggestion-fix',
  rules: rules.conditionalSuggestionFixRules,
};

const fixConfig = {
  name: 'oxlint/fix',
  rules: rules.fixRules,
};

const suggestionConfig = {
  name: 'oxlint/suggestion',
  rules: rules.suggestionRules,
};

const fixDangerousConfig = {
  name: 'oxlint/fix-dangerous',
  rules: rules.fixDangerousRules,
};

const suspiciousConfig = {
  name: 'oxlint/suspicious',
  rules: rules.suspiciousRules,
};

const conditionalSuggestionConfig = {
  name: 'oxlint/conditional-suggestion',
  rules: rules.conditionalSuggestionRules,
};

const dangerousSuggestionConfig = {
  name: 'oxlint/dangerous-suggestion',
  rules: rules.dangerousSuggestionRules,
};

const configByCategory = {
  'flat/pedantic': pedanticConfig,
  'flat/nursery': nurseryConfig,
  'flat/restriction': restrictionConfig,
  'flat/style': styleConfig,
  'flat/conditional-fix': conditionalFixConfig,
  'flat/dangerous-fix': dangerousFixConfig,
  'flat/conditional-fix-suggestion': conditionalFixSuggestionConfig,
  'flat/pending': pendingConfig,
  'flat/correctness': correctnessConfig,
  'flat/perf': perfConfig,
  'flat/conditional-suggestion-fix': conditionalSuggestionFixConfig,
  'flat/fix': fixConfig,
  'flat/suggestion': suggestionConfig,
  'flat/fix-dangerous': fixDangerousConfig,
  'flat/suspicious': suspiciousConfig,
  'flat/conditional-suggestion': conditionalSuggestionConfig,
  'flat/dangerous-suggestion': dangerousSuggestionConfig,
};

export default configByCategory;
