name: Bump oxlint

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: 'The X.Y.Z version to bump to, no `v` prefix.'
        type: string

env:
  OXLINT_PACKAGE_NAME: oxlint

permissions: {}

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false # should be fine, we give another token for PR creation

      - name: Bump Version
        env:
          OXLINT_VERSION: ${{ inputs.version }}
        run: npm version ${OXLINT_VERSION} --no-git-tag-version

      - uses: oxc-project/setup-node@4c26e7cb3605b6bdef5450dacd02c434b10fd8ba # v1.2.0

      - name: Generate version ${{ inputs.version }}
        env:
          OXLINT_VERSION: ${{ inputs.version }}
        run: |
          npm pkg set "peerDependencies.oxlint=~${OXLINT_VERSION}"
          pnpm add oxlint@${OXLINT_VERSION}
          pnpm run generate # Generate rules

      - name: Test and update snapshot
        continue-on-error: true # we check in PR why it fails
        run: pnpm run test -u # Update test snapshots

      - uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: app-token
        with:
          client-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          # bot account with PAT required for triggering workflow runs
          # See https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs
          token: ${{ steps.app-token.outputs.token }}
          commit-message: 'release: v${{ inputs.version }}'
          committer: Boshen <Boshen@users.noreply.github.com>
          author: Boshen <Boshen@users.noreply.github.com>
          branch: release
          branch-suffix: timestamp
          title: 'release: v${{ inputs.version }}'
          assignees: camc314, Sysix
          base: main
