name: Release

on:
  push:
    branches: [main]

permissions: {}

jobs:
  release:
    if: startsWith(github.event.head_commit.message, 'release')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write # for `pnpm publish --provenance`
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: true

      - uses: oxc-project/setup-node@4c588e9266bd930b6ddc34307df0659ed511d187 # v1.3.1

      - name: Build
        run: pnpm run build

      - name: Extract version from commit message
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          VERSION=$(echo "${COMMIT_MESSAGE}" | grep -oP 'release: \Kv[0-9]+\.[0-9]+\.[0-9]+')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create and push tag
        run: |
          git tag ${VERSION}
          git push origin ${VERSION}

      - run: npx changelogithub
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to NPM
        run: pnpm publish --tag latest --provenance --access public
