name: Test

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - uses: oxc-project/setup-node@ab97f03642370d79a7e96dd286bd02a1be40e0ba # v1.3.0

      - name: Run oxlint
        run: pnpm lint

      - name: Run Format (oxfmt)
        run: pnpm format --check

      - name: Run tests
        run: pnpm run test --coverage
